### ISSUE TITLE
FIX Header in CLI during run

### ISSUE THREAD

**Issue by ghost** [ausaafnabi/ML-OverRPC-API#9]
### **Overview**
the log is displayed above header on initialization of the CLI.

#### Severity:
> high

#### Image:
![image](https://user-images.githubusercontent.com/26830685/79067311-17131f80-7cdc-11ea-9ac2-8529b334414e.png)

### Projected Cause:
[utilities.py](https://github.com/ausaafnabi/ML-OverRPC-API/blob/master/utils/utilities.py) might be responsible for this unwanted behavior

### Assigned to:
@Pradyumn3998 
@ausaafnabi

**Comment by ghost** [comment]
the removal of line 31 in utilities.py , seems to fix the problem

**Comment by ausaafnabi** [comment]
Line #31 of utilities.pt might be responsible for this error.....
**Root Cause:** a function call at this line
https://github.com/ausaafnabi/ML-OverRPC-API/blob/1c8016c2608eaf84fc4715151016db8a1f69e995/utils/utilities.py#L31
